In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from google.colab import files
files.upload()

Saving Sales_add.csv to Sales_add.csv

{'Sales_add.csv': b'Month,Region,Manager,Sales_before_digital_add(in $),Sales_After_digital_add(in $)\r\nMonth-1,Region - A,Manager - A,132921,270390\r\nMonth-2,Region - A,Manager - C,149559,223334\r\nMonth-3,Region - B,Manager - A,146278,244243\r\nMonth-4,Region - B,Manager - B,152167,231808\r\nMonth-5,Region - C,Manager - B,159525,258402\r\nMonth-6,Region - A,Manager - B,137163,256948\r\nMonth-7,Region - C,Manager - C,130625,222106\r\nMonth-8,Region - A,Manager - A,131140,230637\r\nMonth-9,Region - B,Manager - C,171259,226261\r\nMonth-10,Region - C,Manager - B,141956,193735\r\nMonth-11,Region - B,Manager - C,159339,203175\r\nMonth-12,Region - A,Manager - A,178939,276279\r\nMonth-13,Region - B,Manager - A,145062,205180\r\nMonth-14,Region - A,Manager - A,151514,253131\r\nMonth-15,Region - C,Manager - A,147463,229336\r\nMonth-16,Region - A,Manager - B,177195,187305\r\nMonth-17,Region - A,Manager - C,140862,234908\r\nMonth-18,Region - C,Manager - B,167996,191517\r\nMonth-19,Region - B,Manager - A,132135,227040\r\nMonth-20,Region - A,Manager - B,152493,212579\r\nMonth-21,Region - B,Manager - A,147425,263388\r\nMonth-22,Region - A,Manager - C,130263,243020'}

In [ ]:
data = pd.read_csv('Sales_add.csv')

In [ ]:
data

,Month,Region,Manager,Sales_before_digital_add(in $),Sales_After_digital_add(in $)
0,Month-1,Region - A,Manager - A,132921,270390
1,Month-2,Region - A,Manager - C,149559,223334
2,Month-3,Region - B,Manager - A,146278,244243
3,Month-4,Region - B,Manager - B,152167,231808
4,Month-5,Region - C,Manager - B,159525,258402
5,Month-6,Region - A,Manager - B,137163,256948
6,Month-7,Region - C,Manager - C,130625,222106
7,Month-8,Region - A,Manager - A,131140,230637
8,Month-9,Region - B,Manager - C,171259,226261
9,Month-10,Region - C,Manager - B,141956,193735
10,Month-11,Region - B,Manager - C,159339,203175
11,Month-12,Region - A,Manager - A,178939,276279
12,Month-13,Region - B,Manager - A,145062,205180
13,Month-14,Region - A,Manager - A,151514,253131
14,Month-15,Region - C,Manager - A,147463,229336
15,Month-16,Region - A,Manager - B,177195,187305
16,Month-17,Region - A,Manager - C,140862,234908
17,Month-18,Region - C,Manager - B,167996,191517
18,Month-19,Region - B,Manager - A,132135,227040
19,Month-20,Region - A,Manager - B,152493,212579
20,Month-21,Region - B,Manager - A,147425,263388
21,Month-22,Region - A,Manager - C,130263,243020

The company needs to check whether there is any dependency between thefeatures “Region” and “Manager”

In [ ]:
from scipy.stats import chi2_contingency

In [ ]:
contingency_table = pd.crosstab(data['Region'],data['Manager'])

In [ ]:
contingency_table

Manager     Manager - A  Manager - B  Manager - C
Region
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1

In [ ]:
from scipy.stats import ttest_rel

In [ ]:
stat, p, dof, expected = chi2_contingency(contingency_table)

print(f"The Test chi-square value is :\t{stat:.3f}")

chi2_critical = 9.488 # the chi2 value at alpha = 0.05 and dof = 4

if stat > chi2_critical:
    print(f" Null Hypothesis Rejected")
elif stat < chi2_critical:
    print ("Null Hypothesis Accepted")

The Test chi-square value is :	3.051
Null Hypothesis Accepted

The company wishes to clarify whether there is any increase in sales after stepping into digital marketing.

In [ ]:
t_sta, p_value = ttest_rel(data['Sales_before_digital_add(in $)'], data['Sales_After_digital_add(in $)'])

In [ ]:
t_sta

-12.09070525287017

In [ ]:
 p_value

6.336667004575778e-11

In [ ]:
if  p_value <0.05:
    print(" Null Hypothesis Rejected")
else:
    print ("Null Hypothesis Accepted")

 Null Hypothesis Rejected